# Generated by Django 3.1.4 on 2020-12-09 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Listing_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Supply_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Weight_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Work_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('unique_item_id', models.IntegerField()),
                ('item_weight', models.FloatField()),
                ('notes', models.CharField(max_length=255)),
                ('item_cost', models.FloatField()),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('shipping_paid', models.FloatField(blank=True, null=True)),
                ('item_paid', models.FloatField(blank=True, null=True)),
                ('final_value_fee', models.FloatField(blank=True, null=True)),
                ('listing_fee', models.FloatField()),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('date_listed', models.DateField()),
                ('returned', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalcapstoneapi.category')),
                ('listing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalcapstoneapi.listing_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalcapstoneapi.weight_type')),
            ],
        ),
        migrations.CreateModel(
            name='Hours_Worked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalcapstoneapi.work_type')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField()),
                ('cost', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='receipt_image')),
                ('supply_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalcapstoneapi.supply_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
