# Generated by Django 3.1.4 on 2020-12-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalcapstoneapi', '0002_auto_20201209_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight_type',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
