# Generated by Django 3.1.4 on 2020-12-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0003_weight_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='returned',
            field=models.NullBooleanField(),
        ),
    ]
