# Generated by Django 3.1.4 on 2021-01-25 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0005_auto_20201211_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='supply_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finalcapstoneapi.supply_type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryitems', to='finalcapstoneapi.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingitems', to='finalcapstoneapi.listing_type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unique_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
