# Generated by Django 3.1.4 on 2021-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0008_auto_20210125_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
