# Generated by Django 3.1.4 on 2021-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0010_auto_20210125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
