# Generated by Django 3.1.4 on 2021-01-26 21:49

from django.db import migrations, models
import finalcapstoneapi.models.item


class Migration(migrations.Migration):

    dependencies = [
        ('finalcapstoneapi', '0012_auto_20210126_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_value_fee',
            field=models.FloatField(blank=True, null=True, validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.FloatField(validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_paid',
            field=models.FloatField(blank=True, null=True, validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_weight',
            field=models.FloatField(validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='listing_fee',
            field=models.FloatField(validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True, validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping_paid',
            field=models.FloatField(blank=True, null=True, validators=[finalcapstoneapi.models.item.Item.validate_value]),
        ),
    ]
